// Hook Library seed data, shown on the LinkedIn > Hooks tab of the Operating System (index.html loads this on first open).
// One hook per line: { text, author }. Gaps to fill in are written as [word], {word} or ___.
window.HOOK_SEEDS = [
  { text: "Handle Every ___ Obstacle Easily Using These Tips", author: "Matt Gray OS" },
  { text: "Mistakes In ___ That Make You Look Stupid", author: "Matt Gray OS" },
  { text: "How To Learn ___ in 5 Minutes", author: "Matt Gray OS" },
  { text: "5 Brilliant Ways To Teach Customers About ___", author: "Matt Gray OS" },
  { text: "3 Ways To Master ___ Without Breaking A Sweat", author: "Matt Gray OS" },
  { text: "How We Improved Our ___ by ___% In One Week", author: "Matt Gray OS" },
  { text: "Want A Thriving Business? Focus On ___!", author: "Matt Gray OS" },
  { text: "___: The Biggest Mistakes", author: "Matt Gray OS" },
  { text: "Wondering How To Make Your ___ Rock? Read This!", author: "Matt Gray OS" },
  { text: "How To Deal With Very Bad ___", author: "Matt Gray OS" },
  { text: "Where Is The Best ___?", author: "Matt Gray OS" },
  { text: "Why You Never See ___ That Actually Works", author: "Matt Gray OS" },
  { text: "The Ultimate Guide To ___", author: "Matt Gray OS" },
  { text: "Nobody Enjoys ___ . How About You?", author: "Matt Gray OS" },
  { text: "How To Sell ___ in 3 Steps", author: "Matt Gray OS" },
  { text: "___ Strategies of The Pros", author: "Matt Gray OS" },
  { text: "Can You Pass This ___ Test?", author: "Matt Gray OS" },
  { text: "Ridiculous Rules About ___ You NEED to Follow", author: "Matt Gray OS" },
  { text: "5 Simple Steps To An Effective ___ Strategy", author: "Matt Gray OS" },
  { text: "Get Better at ___ in 3 Simple Steps", author: "Matt Gray OS" },
  { text: "Learn Exactly How I Improved ___ In 2 Hours", author: "Matt Gray OS" },
  { text: "The Death Of ___. Are You Ready?", author: "Matt Gray OS" },
  { text: "There's Big Money In ___. Learn How to make it!", author: "Matt Gray OS" },
  { text: "Clear And Unbiased Facts About ___ (No BS)", author: "Matt Gray OS" },
  { text: "What Zombies Can Teach You About ___", author: "Matt Gray OS" },
  { text: "___ Secrets You Never Knew", author: "Matt Gray OS" },
  { text: "The Top Secrets of ___", author: "Matt Gray OS" },
  { text: "The Secret of Successful ___", author: "Matt Gray OS" },
  { text: "Don't Just Sit There! Start ___", author: "Matt Gray OS" },
  { text: "The Tony Robbins Guide To ___", author: "Matt Gray OS" },
  { text: "Mysteries of ___ Revealed", author: "Matt Gray OS" },
  { text: "The Truth Is You Are Not The Only Person Who Sucks at ___", author: "Matt Gray OS" },
  { text: "Fall In Love With These ___ Tips", author: "Matt Gray OS" },
  { text: "The Most Irresistible ___", author: "Matt Gray OS" },
  { text: "How You Can Do ___ In 24 Hours For Free", author: "Matt Gray OS" },
  { text: "4 Best Ways To Sell ___", author: "Matt Gray OS" },
  { text: "Want ___? ___ Will Help You Get There", author: "Matt Gray OS" },
  { text: "The Jaw-Dropping Truth About ___ In 3 Minutes", author: "Matt Gray OS" },
  { text: "Some People Excel At ___ And Some Don't – Learn Why", author: "Matt Gray OS" },
  { text: "Could This Report Be The Definitive Answer To Your MARKETING?", author: "Matt Gray OS" },
  { text: "7 Things You Have In Common With ___", author: "Matt Gray OS" },
  { text: "How To Find The Right ___ For Your ___", author: "Matt Gray OS" },
  { text: "Interesting Facts I Bet You Don't Know About ___", author: "Matt Gray OS" },
  { text: "How To Save Money with ___ (Yes, For Real)", author: "Matt Gray OS" },
  { text: "It's All About ___", author: "Matt Gray OS" },
  { text: "___ Will Explode Your Business", author: "Matt Gray OS" },
  { text: "The Best People to Ever Do ___", author: "Matt Gray OS" },
  { text: "There's a Big Mystery Around ___", author: "Matt Gray OS" },
  { text: "The Ultimate Deal On ___", author: "Matt Gray OS" },
  { text: "Turn Your ___ Into A Money Making Machine", author: "Matt Gray OS" },
  { text: "Why Everything You Know About ___ Is A Lie", author: "Matt Gray OS" },
  { text: "Marriage And ___ Have More In Common Than You Think", author: "Matt Gray OS" },
  { text: "5 Ways ___ Can Make You Invincible", author: "Matt Gray OS" },
  { text: "Essential ___ For ___", author: "Matt Gray OS" },
  { text: "Make Customers Drool With ___", author: "Matt Gray OS" },
  { text: "8 Unheard Ways to ___", author: "Matt Gray OS" },
  { text: "The Next Billion-Dollar Secret For ___", author: "Matt Gray OS" },
  { text: "Want More ___? Then Do This", author: "Matt Gray OS" },
  { text: "Your ___ Doesn't Want You to Read This Ad", author: "Matt Gray OS" },
  { text: "You Can Achieve ___ In Just ___ Days With ___", author: "Matt Gray OS" },
  { text: "17 Tricks About ___ You Wish You Knew Before", author: "Matt Gray OS" },
  { text: "Stop Wasting Time And Start Doing ___", author: "Matt Gray OS" },
  { text: "5 Sexy Ways To Improve Your ___", author: "Matt Gray OS" },
  { text: "Would You Like to Have a ___?", author: "Matt Gray OS" },
  { text: "World Renowned ___ Reveals His Secrets to ___", author: "Matt Gray OS" },
  { text: "How To Turn ___ From Zero To Hero", author: "Matt Gray OS" },
  { text: "The Stupid-Siple Guide To ___", author: "Matt Gray OS" },
  { text: "The Lazy Man's Guide To ___", author: "Matt Gray OS" },
  { text: "Who Else Wants To Finally Enjoy ___?", author: "Matt Gray OS" },
  { text: "Why Lazy People Succeed The Most in ___", author: "Matt Gray OS" },
  { text: "14 Tips For Massive ___ Success", author: "Matt Gray OS" },
  { text: "Beware The ___ Scam", author: "Matt Gray OS" },
  { text: "The Philosophy Of ___", author: "Matt Gray OS" },
  { text: "Avoid The Top 12 ___ Mistakes", author: "Matt Gray OS" },
  { text: "Secrets To Getting ___ Off Your Mind Forever", author: "Matt Gray OS" },
  { text: "Don't Fall For This New Advanced ___ Scam", author: "Matt Gray OS" },
  { text: "Why We're Giving Away ___ to Help You ___", author: "Matt Gray OS" },
  { text: "Do You Want ___ With Little Effort?", author: "Matt Gray OS" },
  { text: "Do You Have a Problem With ___? Try This", author: "Matt Gray OS" },
  { text: "2 Easy Ways To Make ___ Faster", author: "Matt Gray OS" },
  { text: "Don't Be Fooled By ___", author: "Matt Gray OS" },
  { text: "Find A Quick Way To ___", author: "Matt Gray OS" },
  { text: "3 Ways Facebook Destroyed My ___ Without Me Noticing", author: "Matt Gray OS" },
  { text: "What Everyone Ought To Know About ___", author: "Matt Gray OS" },
  { text: "Thank Me Later – 3 Reasons To Stop Thinking About ___", author: "Matt Gray OS" },
  { text: "___ And The Chuck Norris Effect", author: "Matt Gray OS" },
  { text: "You Don't Have To Be A Millionaire To Start ___", author: "Matt Gray OS" },
  { text: "A Surprising Tool To Help You ___", author: "Matt Gray OS" },
  { text: "___: The Samurai Way", author: "Matt Gray OS" },
  { text: "Now You Can Have The ___ Of Your Dreams", author: "Matt Gray OS" },
  { text: "2 Things You Must Know About ___", author: "Matt Gray OS" },
  { text: "Little Known Ways To Rid Yourself Of ___", author: "Matt Gray OS" },
  { text: "What Customers Really Think About Your ___", author: "Matt Gray OS" },
  { text: "5 Actionable Tips on ___ And ___", author: "Matt Gray OS" },
  { text: "Get Ahead Your Competition Instantly by ___", author: "Matt Gray OS" },
  { text: "The Biggest Lie In ___ (You Believe It)", author: "Matt Gray OS" },
  { text: "How To Start A Business With ___", author: "Matt Gray OS" },
  { text: "To People That Want To Start ___ But Are Afraid To Get Started", author: "Matt Gray OS" },
  { text: "How To Make Your ___ Look Amazing In 3 Days", author: "Matt Gray OS" },
  { text: "16 Tips To Start Building A ___ Empire", author: "Matt Gray OS" },
  { text: "5 Problems Everyone Has With ___ (Solved)", author: "Matt Gray OS" },
  { text: "Why You Absolutely Need to Buy a Used ___", author: "Matt Gray OS" },
  { text: "Everything You Wanted to Know About ___ and Were Afraid To Ask", author: "Matt Gray OS" },
  { text: "Sick And Tired Of ___? Read This", author: "Matt Gray OS" },
  { text: "Solve Any ___ Problem With ___", author: "Matt Gray OS" },
  { text: "How To Teach ___ Like A Pro", author: "Matt Gray OS" },
  { text: "The Hidden Mystery Behind ___", author: "Matt Gray OS" },
  { text: "Take 10 Minutes to Get Started With ___", author: "Matt Gray OS" },
  { text: "Boost ___ in 5 Minutes Flat", author: "Matt Gray OS" },
  { text: "5 Brilliant Ways To Use ___", author: "Matt Gray OS" },
  { text: "5 Romantic ___ Ideas", author: "Matt Gray OS" },
  { text: "The Most Fascinating Discovery Was Just Made About ___ Did You Hear?", author: "Matt Gray OS" },
  { text: "How To Win Clients And Influence ___ With ___", author: "Matt Gray OS" },
  { text: "The Next 3 Things To Immediately Do About ___", author: "Matt Gray OS" },
  { text: "At Last, The Secret To ___ Is Revealed", author: "Matt Gray OS" },
  { text: "The Untold Secret To ___ In Less Than 5 Minutes", author: "Matt Gray OS" },
  { text: "Where The ___ is And How to Get It", author: "Matt Gray OS" },
  { text: "Make Your ___ Dream A Reality", author: "Matt Gray OS" },
  { text: "Which One of These ___ Problems Do You Have?", author: "Matt Gray OS" },
  { text: "Would You Rather ___ or ___?", author: "Matt Gray OS" },
  { text: "What Everyone Must Know About ___", author: "Matt Gray OS" },
  { text: "Where Can You Find Free ___ Resources", author: "Matt Gray OS" },
  { text: "Top 10 Tips To Grow Your ___ Silly Fast", author: "Matt Gray OS" },
  { text: "This Study Just Found ___: Read Or Miss Out", author: "Matt Gray OS" },
  { text: "We're Looking For People Who Want To ___ With ___", author: "Matt Gray OS" },
  { text: "Wanted – ___!", author: "Matt Gray OS" },
  { text: "Want To Be A ___?", author: "Matt Gray OS" },
  { text: "Turn your ___ into a ___", author: "Matt Gray OS" },
  { text: "To People Who Want To ___ But Can't Get Started", author: "Matt Gray OS" },
  { text: "This ___ Makes ___ So ___, I Bought It For My Wife!", author: "Matt Gray OS" },
  { text: "They Laughed When I ___ – But When I ___", author: "Matt Gray OS" },
  { text: "Lies And Damn Lies About ___", author: "Matt Gray OS" },
  { text: "Your Key To Peace: ___", author: "Matt Gray OS" },
  { text: "There's Big ___ In ___", author: "Matt Gray OS" },
  { text: "The Secret to ___ Is Simply ___!", author: "Matt Gray OS" },
  { text: "The Revolutionary New ___ The Worlds ___ Use", author: "Matt Gray OS" },
  { text: "The Quickest Way I Know To ___", author: "Matt Gray OS" },
  { text: "The ___ all ___ is talking about", author: "Matt Gray OS" },
  { text: "The Art Of ___", author: "Matt Gray OS" },
  { text: "The Amazing Story Of ___", author: "Matt Gray OS" },
  { text: "The Amazing ___ That Will Fool ___", author: "Matt Gray OS" },
  { text: "Do You Have These Symptoms Of ___?", author: "Matt Gray OS" },
  { text: "Do You Honestly Want To ___?", author: "Matt Gray OS" },
  { text: "Fact-Filled ___ Reveals How To ___", author: "Matt Gray OS" },
  { text: "Finally, The Greatest ___", author: "Matt Gray OS" },
  { text: "Find Out How Thousands Finally ___", author: "Matt Gray OS" },
  { text: "Free ___ Tells You 17 Secrets Of ___", author: "Matt Gray OS" },
  { text: "Get A ___ WITHOUT ___", author: "Matt Gray OS" },
  { text: "Greatest Goldmine of ___", author: "Matt Gray OS" },
  { text: "Here's A Way To ___ That Has Never Failed", author: "Matt Gray OS" },
  { text: "How A New Discovery Made ___", author: "Matt Gray OS" },
  { text: "The Step by Step Guide to ___", author: "Matt Gray OS" },
  { text: "How To ___ Minute by Minute", author: "Matt Gray OS" },
  { text: "How To ___ In Three Months", author: "Matt Gray OS" },
  { text: "How To Get Out of ___ Today", author: "Matt Gray OS" },
  { text: "Get a Free ___ When You ___!", author: "Matt Gray OS" },
  { text: "How to Get The ___ of Your Dreams in ___", author: "Matt Gray OS" },
  { text: "How To Have A ___", author: "Matt Gray OS" },
  { text: "How To Master The Art of ___", author: "Matt Gray OS" },
  { text: "___ Your Way To Success", author: "Matt Gray OS" },
  { text: "3 Rules About ___ Meant To Be Broken", author: "Matt Gray OS" },
  { text: "Fast-Track Your ___", author: "Matt Gray OS" },
  { text: "No More Mistakes With ___", author: "Matt Gray OS" },
  { text: "Answered: Your Most Burning Questions About ___", author: "Matt Gray OS" },
  { text: "Master ___ in 5 Minutes A Day", author: "Matt Gray OS" },
  { text: "3 Things Everyone Knows About ___ That You Don't", author: "Matt Gray OS" },
  { text: "The Untold Secret To Mastering ___ In Just 3 Days", author: "Matt Gray OS" },
  { text: "How To Quit ___ In 5 Days", author: "Matt Gray OS" },
  { text: "The ___ That Wins Customers", author: "Matt Gray OS" },
  { text: "3 Ways To Have More Appealing ___", author: "Matt Gray OS" },
  { text: "Little Known Ways to ___", author: "Matt Gray OS" },
  { text: "How To ___ Legally", author: "Matt Gray OS" },
  { text: "Take The Headache Out Of ___", author: "Matt Gray OS" },
  { text: "How To Turn ___ Into ___", author: "Matt Gray OS" },
  { text: "Can You Pass This ___ Test?", author: "Matt Gray OS" },
  { text: "Confessions Of A ___", author: "Matt Gray OS" },
  { text: "Own Your Own ___", author: "Matt Gray OS" },
  { text: "Remember When You Could Have ___, And You Didn't?", author: "Matt Gray OS" },
  { text: "___ Got You Down? We Have The Solution", author: "Matt Gray OS" },
  { text: "Warning: These 9 Mistakes Will Destroy Your ___", author: "Matt Gray OS" },
  { text: "Sick And Tired Of ___?", author: "Matt Gray OS" },
  { text: "10 Unforgivable Sins Of ___", author: "Matt Gray OS" },
  { text: "Learn How to Build Your Own ___", author: "Matt Gray OS" },
  { text: "Download Your Free Copy of The ___ 11 Methods Of MARKETING Domination", author: "Matt Gray OS" },
  { text: "Why My ___ Is Better Than Yours", author: "Matt Gray OS" },
  { text: "Why Ignoring ___ Will Cost You Time and Sales", author: "Matt Gray OS" },
  { text: "Double Your Profit With These 5 Tips on ___", author: "Matt Gray OS" },
  { text: "___ Shortcuts – The Easy Way", author: "Matt Gray OS" },
  { text: "Got Stuck? Try These Tips To ___", author: "Matt Gray OS" },
  { text: "A Collection of 1,000+ Resources on ___", author: "Matt Gray OS" },
  { text: "Build a 7 Figure Income Doing ___ In Your Pjamas", author: "Matt Gray OS" },
  { text: "Why ___ Is The Only Skill You Really Need", author: "Matt Gray OS" },
  { text: "How I Improved My ___ In One Easy Lesson", author: "Matt Gray OS" },
  { text: "How You Can Do ___ Almost Instantly", author: "Matt Gray OS" },
  { text: "Make Money From ___", author: "Matt Gray OS" },
  { text: "Succeed With ___ In 24 Hours", author: "Matt Gray OS" },
  { text: "3 Easy Ways To Make ___ Automated", author: "Matt Gray OS" },
  { text: "The Best Way To ___", author: "Matt Gray OS" },
  { text: "How To Make Your Product Stand Out With ___", author: "Matt Gray OS" },
  { text: "A Little Mistake That Cost ___ Over ___ Per Year", author: "Matt Gray OS" },
  { text: "10 Ways To Reinvent Your ___", author: "Matt Gray OS" },
  { text: "What Is ___ and How Does It Work?", author: "Matt Gray OS" },
  { text: "Should Fixing ___ Take 60 Steps? (We Don't Think So)", author: "Matt Gray OS" },
  { text: "13 Lessons About ___ You Need To Learn To Succeed", author: "Matt Gray OS" },
  { text: "Proof That ___ Really Does Work", author: "Matt Gray OS" },
  { text: "Do You Have The Courage to ___?", author: "Matt Gray OS" },
  { text: "You're Losing Because You ___ Every Day", author: "Matt Gray OS" },
  { text: "Rules Not To Follow About ___", author: "Matt Gray OS" },
  { text: "Top 20 Quotes On ___", author: "Matt Gray OS" },
  { text: "The World's Easiest ___", author: "Matt Gray OS" },
  { text: "Don't Pay a Penny For ___", author: "Matt Gray OS" },
  { text: "Instant ___!", author: "Matt Gray OS" },
  { text: "How to Say Goodbye to Your ___", author: "Matt Gray OS" },
  { text: "Throw Away Your ___", author: "Matt Gray OS" },
  { text: "Why ___ Is No Friend To ___", author: "Matt Gray OS" },
  { text: "Get The Most Out of ___ and ___", author: "Matt Gray OS" },
  { text: "10 Best Practices For ___", author: "Matt Gray OS" },
  { text: "OMG! The Best ___ Ever!", author: "Matt Gray OS" },
  { text: "How To Lose Money With ___", author: "Matt Gray OS" },
  { text: "How To Make More ___ By Doing Less", author: "Matt Gray OS" },
  { text: "___: This Is What Professionals Do", author: "Matt Gray OS" },
  { text: "Why Haven't More People Been Doing ___?", author: "Matt Gray OS" },
  { text: "3 Ways You Can Reinvent ___ Without Looking Like An Amateur", author: "Matt Gray OS" },
  { text: "10 Funny ___ Quotes", author: "Matt Gray OS" },
  { text: "How to Buy ___ For Cheap", author: "Matt Gray OS" },
  { text: "Hilarious ___ Adventures", author: "Matt Gray OS" },
  { text: "Change Your Life By ___", author: "Matt Gray OS" },
  { text: "How to Eat Your Way Out of ___", author: "Matt Gray OS" },
  { text: "From ___ to ___ in 6 Hours", author: "Matt Gray OS" },
  { text: "Create Your Own ___ By ___", author: "Matt Gray OS" },
  { text: "___ Revealed at Last!", author: "Matt Gray OS" },
  { text: "___ – So Simple Even Kids Can Do It", author: "Matt Gray OS" },
  { text: "Famous ___ Tells All About ___", author: "Matt Gray OS" },
  { text: "How to Get Over Your Fear of ___ For Good", author: "Matt Gray OS" },
  { text: "Introducing ___", author: "Matt Gray OS" },
  { text: "Introducing The World's First ___", author: "Matt Gray OS" },
  { text: "Don't ___ Again Until You Read This Article", author: "Matt Gray OS" },
  { text: "What The ___ Aren't Telling You About ___", author: "Matt Gray OS" },
  { text: "Never Do ___ Again After Knowing This", author: "Matt Gray OS" },
  { text: "Don't Miss Out on ___", author: "Matt Gray OS" },
  { text: "___ Only Available While Times Lasts!", author: "Matt Gray OS" },
  { text: "Does ___ Sometimes Make You Feel Stupid?", author: "Matt Gray OS" },
  { text: "Are You Embarrassed By Your ___? Here's The Cure", author: "Matt Gray OS" },
  { text: "Open The Gates For ___ By Using These Simple Tips", author: "Matt Gray OS" },
  { text: "Learn How To Start ___", author: "Matt Gray OS" },
  { text: "5 Ways To Keep Your ___ Without Burning The Midnight Oil", author: "Matt Gray OS" },
  { text: "Never Lose Your ___ Again", author: "Matt Gray OS" },
  { text: "Is ___ Worth $___ To You?", author: "Matt Gray OS" },
  { text: "They Told Me ___, So I ___", author: "Matt Gray OS" },
  { text: "Why You Really Need ___", author: "Matt Gray OS" },
  { text: "You Don't Need ___, You Need ___", author: "Matt Gray OS" },
  { text: "5 Reasons ___ Is A Waste Of Time", author: "Matt Gray OS" },
  { text: "Here Is A Method That Is Helping ___ do ___", author: "Matt Gray OS" },
  { text: "Here Is A Quick Cure For ___", author: "Matt Gray OS" },
  { text: "What Can You Do About Your ___ Right Now", author: "Matt Gray OS" },
  { text: "Learn Exactly How I Made $___ Last Month", author: "Matt Gray OS" },
  { text: "In 10 Minutes, I'll Give You The Truth About ___", author: "Matt Gray OS" },
  { text: "Keep Your Family and Children Safe With ___", author: "Matt Gray OS" },
  { text: "___ Expert Interview", author: "Matt Gray OS" },
  { text: "What You Can Learn From Bill Gates About ___", author: "Matt Gray OS" },
  { text: "If ___ Is So Terrible, Why Does Science Say Otherwise?", author: "Matt Gray OS" },
  { text: "How To Earn $___ Day Using ___", author: "Matt Gray OS" },
  { text: "The Ugly Truth About ___", author: "Matt Gray OS" },
  { text: "Why I Hate ___", author: "Matt Gray OS" },
  { text: "How To Take The Headache Out Of ___", author: "Matt Gray OS" },
  { text: "Do ___ Better Than Steve Jobs", author: "Matt Gray OS" },
  { text: "The President Does ___. Do You?", author: "Matt Gray OS" },
  { text: "Revolutionize Your ___ With These Mind-Blowing Tips", author: "Matt Gray OS" },
  { text: "Crack The ___ Code", author: "Matt Gray OS" },
  { text: "Warning Signs Of Your ___ Demise", author: "Matt Gray OS" },
  { text: "If You Don't ___, You Will Hate Yourself Later", author: "Matt Gray OS" },
  { text: "Get Rid of ___ For Good", author: "Matt Gray OS" },
  { text: "How To ___ On A Tight Budget", author: "Matt Gray OS" },
  { text: "Old School ___", author: "Matt Gray OS" },

  { text: "[Subject] started with [limited resource / nothing] and still gave me [everything / full support]. This [milestone] is for them.", author: "Lara Acosta" },
  { text: "I've read many books, but this one [had X impact]: (And it's not [what people expect])", author: "Lara Acosta" },
  { text: "[X time] ago, I decided to [commit to something]. Today I reached [X goal/milestone]!", author: "Lara Acosta" },
  { text: "pov: you become [achievement your audience wants]", author: "Lara Acosta" },
  { text: "My [business/platform/career] grew by [X] in [timeframe]. My [other platform/business] is estimated to do the same next. Here's exactly how I'm doing it", author: "Lara Acosta" },
  { text: "This is exactly why I became a [role/identity].", author: "Lara Acosta" },
  { text: "Attended my first [event] [time ago]. [Specific line to show how far you've come]!", author: "Lara Acosta" },
  { text: "This is one of my biggest competitors in [industry/niche]. But they also [counter-intuitive thing about them]", author: "Lara Acosta" },
  { text: "Age [X]: Couldn't [struggle 1]. Felt [emotion].", author: "Lara Acosta" },
  { text: "[Time period] ago, I didn't think [thing in your industry] was possible", author: "Lara Acosta" },
  { text: "If you don't have [thing people think they need], read this: The [best people in demographic] I know don't have it either", author: "Lara Acosta" },
  { text: "I failed [specific credential/exam] took. A few things I've done despite it:", author: "Lara Acosta" },
  { text: "I [failed/got rejected at] (nearly) [what you tried in the past]", author: "Lara Acosta" },
  { text: "I [achieved outcome] in record time. (without [expected requirement])", author: "Lara Acosta" },
  { text: "This was my first [attempt at x thing you do]. I still cringe at it. That same [cringe] [helped you achieve outcome]", author: "Lara Acosta" },
  { text: "My [relatable thing people struggle with] I [struggle with relatable bad habit 1] I [struggle with relatable bad habit 2] I [struggle with relatable bad habit 3]", author: "Lara Acosta" },
  { text: "I failed to get [X dream goal] at [age]. Now, I'm [full circle moment / achieving x].", author: "Lara Acosta" },
  { text: "pov: you woke up on [date/moment] and decided to change. this [object] is a daily reminder of what is possible.", author: "Lara Acosta" },
  { text: "[X person] was doing what I wanted, I was struggling to [get outcome]. [Time period, I met/connected/found x person]", author: "Lara Acosta" },
  { text: "[Year]: [struggling/failing before outcome] [Year]: [succeeding/achievement after outcome]", author: "Lara Acosta" },
  { text: "Confession: I don't think [X industry] is [what people expect to think]", author: "Lara Acosta" },
  { text: "My #1 [industry] rule is [X].", author: "Lara Acosta" },
  { text: "I just did [video/interview/podcast/livestream]! But you don't have [X time] so...", author: "Lara Acosta" },
  { text: "I understand why people [struggle/quit x thing] in your industry. I do.", author: "Lara Acosta" },
  { text: "I learned [skill] [an uncommon way]", author: "Lara Acosta" },
  { text: "My [career/journey] wasn't always good.", author: "Lara Acosta" },
  { text: "I successfully broke every \"rule\" in [X industry].", author: "Lara Acosta" },
  { text: "[X time] ago today, I [previous milestone]", author: "Lara Acosta" },
  { text: "In the last [time period], my [life/career] completely changed. (I wish this post could time travel back)", author: "Lara Acosta" },
  { text: "Most of you don't know I [did a thing]. I did so [time frame].", author: "Lara Acosta" },
  { text: "Before being a [current role], I was a [past unrelated role].", author: "Lara Acosta" },
  { text: "[Time period] ago, I [past situation contrasting your current situation]", author: "Lara Acosta" },
  { text: "I [did cool thing] this year (and not everyone understands WHY)", author: "Lara Acosta" },
  { text: "I've been [doing x] for [x] years.", author: "Lara Acosta" },
  { text: "This is what a \"busy\" day in a life looks like for me. (As a [demographic/identity] living in [location]).", author: "Lara Acosta" },
  { text: "Today is one of the [adjective] moments of my [specific pursuit]. After [time period] of effortful endeavours... After [countless specific challenges]... After [seeing impressive outcomes]... I've finally [achieved milestone/created something].", author: "Lara Acosta" },
  { text: "My first [time period] doing [activity], I [achieved very little/nothing]. The next [time period] → [small milestone]. The next [time period] → [bigger milestone]. By the end of [larger timeframe] → [massive milestone]. But I could've done it quicker. Here are the mistakes I'd avoid (if starting over from scratch):", author: "Lara Acosta" },
  { text: "I'm sorry. I've been keeping a [secret/confession] I shouldn't have. But every time I mention it, no one believes me", author: "Lara Acosta" },
  { text: "I used to think I was too \"[trait]\" to [do common industry thing]", author: "Lara Acosta" },
  { text: "I failed - I thought my [career/goal] was over", author: "Lara Acosta" },

  { text: "[X] steps to build a $[Y]/month [outcome]:", author: "Matt Gray" },
  { text: "[X] mental models that killed my [problem] forever:", author: "Matt Gray" },
  { text: "[X] habits that (quietly) changed my life forever:", author: "Matt Gray" },
  { text: "[X] parts of a successful [asset]:", author: "Matt Gray" },
  { text: "[X] habits that will transform your life in [timeframe]:", author: "Matt Gray" },
  { text: "[X] ways to [transform something] (based on science):", author: "Matt Gray" },
  { text: "Great [role] have [X] clear signs that set them apart:", author: "Matt Gray" },
  { text: "[X] secrets to become [desired trait]:", author: "Matt Gray" },
  { text: "[X] habits that will make you [desired state] than [Y]% of people:", author: "Matt Gray" },
  { text: "[X] clear signs you have a great [role]:", author: "Matt Gray" },
  { text: "The [X] most powerful [category] I've discovered:", author: "Matt Gray" },
  { text: "[X] ways to stop [bad behavior] and [desired speed outcome], without breaking your [asset]:", author: "Matt Gray" },
  { text: "I made $[X] from a [asset/tactic] most [peer group] treat like an afterthought.", author: "Matt Gray" },
  { text: "I built a [asset] that reaches [X] people every [timeframe].", author: "Matt Gray" },
  { text: "I grew my [platform] to [X]+ [metric] posting [frequency] (without [downside avoided])", author: "Matt Gray" },
  { text: "I create [X] pieces of [asset] per [timeframe].", author: "Matt Gray" },
  { text: "I [did activity] [X] times in a [timeframe], here's which ones you should [replicate verb]:", author: "Matt Gray" },
  { text: "I've worked with [X] [people type] over the [timeframe].", author: "Matt Gray" },
  { text: "I spent nearly [X] [time unit] [doing thing] the hard way.", author: "Matt Gray" },
  { text: "I can teach you more in [short time] than you'll learn in [long time].", author: "Matt Gray" },
  { text: "You'd make more [result] if your [asset] needed less of you.", author: "Matt Gray" },
  { text: "The [practitioners] who build the biggest [outcome type] eventually stop thinking like [starting identity].", author: "Matt Gray" },
  { text: "You're wasting [X]% of your best [asset].", author: "Matt Gray" },
  { text: "Most [role] think [desired outcome] comes from more [common input]. It doesn't. It comes from [counter-intuitive input], done better.", author: "Matt Gray" },
  { text: "Most people don't have a [assumed problem] problem.", author: "Matt Gray" },
  { text: "Most [thing] don't [fail outcome] from [assumed cause].", author: "Matt Gray" },
  { text: "Most [role] think they're building a [assumed thing].", author: "Matt Gray" },
  { text: "Most [role] build a [asset] and hope [desired outcome] follows.", author: "Matt Gray" },
  { text: "Most [role] build [asset] that solve the wrong [problem].", author: "Matt Gray" },
  { text: "Most people chase [decoy target].", author: "Matt Gray" },
  { text: "People often think [common tactic] is the answer.", author: "Matt Gray" },
  { text: "There's a reason your best [output] still don't lead to [desired outcome].", author: "Matt Gray" },
  { text: "The best [role] I know are secretly [counter-intuitive trait].", author: "Matt Gray" },
  { text: "Your best [output] don't come from more [common but wrong input].", author: "Matt Gray" },
  { text: "[Simple tool] are the new [modern system].", author: "Matt Gray" },
  { text: "[Good input] are the new [modern crutch].", author: "Matt Gray" },
  { text: "You're not [assumed diagnosis/label].", author: "Matt Gray" },
  { text: "You are going to [inevitable truth].", author: "Matt Gray" },
  { text: "Nobody is coming to [rescue action] you.", author: "Matt Gray" },
  { text: "You can't build a sustainable [outcome] on an unsustainable [foundation].", author: "Matt Gray" },
  { text: "If you are in your [age range], stop [bad behavior].", author: "Matt Gray" },
  { text: "If you don't have [foundational input], you'll never be a [status level] [role].", author: "Matt Gray" },
  { text: "I used to be [state 1], [state 2], and [state 3].", author: "Matt Gray" },
  { text: "I posted every day for [timeframe] and [result] almost nothing.", author: "Matt Gray" },
  { text: "I used to collect [inputs] like [status objects].", author: "Matt Gray" },
  { text: "My [external metric] was growing, but I was falling apart [internally].", author: "Matt Gray" },
  { text: "For [timeframe] I mistook [decoy trait] for [real goal].", author: "Matt Gray" },
  { text: "[Role] are terrified [threat] will replace them.", author: "Matt Gray" },
  { text: "Plenty of [role] are using [tool/trend] wrong.", author: "Matt Gray" },
  { text: "Most [role] are winging their [asset].", author: "Matt Gray" },
  { text: "Most [role] waste their [timeframe] [asset].", author: "Matt Gray" },
  { text: "[Asset/venture] usually fail at the same [moment/stage].", author: "Matt Gray" },
  { text: "I spent [timeframe] [doing thing] before I understood this:", author: "Matt Gray" },
  { text: "The biggest improvement in my [life area] came when I realized [outcome] is just a product of [input].", author: "Matt Gray" },
  { text: "Last [day], I took my [item 1], my [item 2], and [action] [distance] [direction] with no plan.", author: "Matt Gray" },
  { text: "I was on a [interaction type] with a [role] doing $[X]/[timeframe].", author: "Matt Gray" },
  { text: "If I could go back and tell [age]-year-old [name] what actually matters, here's what I'd say:", author: "Matt Gray" },
  { text: "The best [role] I've ever had gave me [tool] I could [use verb] that [timeframe].", author: "Matt Gray" },
  { text: "I learned [lesson type] the hard way.", author: "Matt Gray" },
  { text: "Here's how to build a plan for [time period] to actually achieve your [goal type]:", author: "Matt Gray" },
  { text: "Here's how to become the most [status] [role] in your [niche]:", author: "Matt Gray" },
  { text: "Here's how to [desired outcome] (without [feared tradeoff]):", author: "Matt Gray" },
  { text: "Here's how I turned [asset] into a predictable [outcome] engine:", author: "Matt Gray" },
  { text: "Here's how I organize my entire [timeframe] in one [tool]:", author: "Matt Gray" },
  { text: "Here's how to actually use [tool/trend] to build a [desired outcome] in [year]:", author: "Matt Gray" },
  { text: "How to design your dream [outcome] in [year].", author: "Matt Gray" },
  { text: "How to develop [trait] as a [role]:", author: "Matt Gray" },
  { text: "[Skill/outcome] is simple when you understand this secret:", author: "Matt Gray" },
  { text: "[Authority name] once said:", author: "Matt Gray" },
  { text: "[Skill] is one of the highest-leverage skills a [role] can learn.", author: "Matt Gray" },
  { text: "[Concept] is a [mechanism A], not a [mechanism B].", author: "Matt Gray" },
  { text: "A lesson I wish I learned earlier: [insight].", author: "Matt Gray" },
  { text: "Every [pattern] you have was built the same way.", author: "Matt Gray" },
  { text: "Going all-in on [thing] built everything I have.", author: "Matt Gray" },
  { text: "Being surrounded by the right [resource] is the best hack for ultimate [outcome].", author: "Matt Gray" },
  { text: "The [role] winning on [platform] in [year] have one thing in common.", author: "Matt Gray" },
  { text: "You can hire a team of [top-tier resource], but if your [process] is vague, they can't move without you.", author: "Matt Gray" },
  { text: "[Concept name] is a [origin/culture] concept.", author: "Matt Gray" },
  { text: "Most people wake up and ask, \"[common weak question]?\"", author: "Matt Gray" },
  { text: "For [timeframe] I [did habitual action] like my life depended on it.", author: "Matt Gray" },
  { text: "[X] steps to design the [life/outcome] you want:", author: "Matt Gray" },
  { text: "I wasted my [decade] building [other people's dreams]. At [age], I finally built mine.", author: "Matt Gray" },
  { text: "I audited a [role]'s [asset] last [timeframe].", author: "Matt Gray" },
  { text: "The bottleneck in your [asset] isn't [assumed cause].", author: "Matt Gray" },
  { text: "I'm [age].", author: "Matt Gray" },
  { text: "For [timeframe], I confused [concept A] with [concept B].", author: "Matt Gray" },
  { text: "Most [role] aren't short on [resource].", author: "Matt Gray" },
  { text: "Most [role] I talk to share the same hidden [problem].", author: "Matt Gray" },
  { text: "Most [role] treat their [asset] like a [hobby/decoy].", author: "Matt Gray" },
  { text: "For [timeframe], I tried to live every [period] like it was my [reference period].", author: "Matt Gray" },
  { text: "There was a [season/period] in my life where I wanted to [give up action] every single day.", author: "Matt Gray" },
  { text: "I burned out at [age] because I couldn't [let go/desired behavior].", author: "Matt Gray" },
  { text: "I'm convinced the biggest reason I was able to build [X] [asset] was through [trait/input].", author: "Matt Gray" },
  { text: "[X] AI skills to multiply your output in [year]:", author: "Matt Gray" },
  { text: "I was working [X]-hour days.", author: "Matt Gray" },
  { text: "I make $[X]/[timeframe] while taking [Y]-day weekends.", author: "Matt Gray" },
  { text: "The best [category] you can develop is [action/skill].", author: "Matt Gray" },
  { text: "[Skill] is a superpower.", author: "Matt Gray" },
  { text: "Most successful people aren't more [trait] than you.", author: "Matt Gray" },
  { text: "I asked myself a question that changed everything.", author: "Matt Gray" },
  { text: "The day I [did specific action] from [location], I knew I'd failed.", author: "Matt Gray" },
  { text: "[Mundane childhood task] taught me more than any [credential].", author: "Matt Gray" },
  { text: "[Goal] is simple. Just become the [person/thing] everyone [refers/wants].", author: "Matt Gray" },
  { text: "My friend [name] flew to [location] to get my help with one goal.", author: "Matt Gray" },
  { text: "Your [asset] is burning you out.", author: "Matt Gray" },
  { text: "Become a [skill] genius by stealing my \"[Framework Name]\".", author: "Matt Gray" },
  { text: "Most [role] launch [asset] that attract the wrong [target].", author: "Matt Gray" },
  { text: "I used to work [X]-hour days and have constant [negative state]. Now I work less than [Y] hours a day, and my [asset] are growing bigger than ever.", author: "Matt Gray" },
  { text: "There are [X] [category] phrases every [role] should know.", author: "Matt Gray" },
  { text: "[X] [timeframe] spent in [location] changed the way I think about [topic].", author: "Matt Gray" },
  { text: "I'm hiring a [role].", author: "Matt Gray" },
  { text: "A mentor once told me that successful [role] are [trait].", author: "Matt Gray" },
  { text: "[Resource] without [meaning/purpose] is [negative state].", author: "Matt Gray" },
  { text: "How to build a [X]-person team that creates [Y]+ pieces of [asset] per [timeframe]:", author: "Matt Gray" },
  { text: "When I started sharing my exact [asset] openly, something unexpected happened.", author: "Matt Gray" },
  { text: "What worked in [year A] is obsolete in [year B].", author: "Matt Gray" },
  { text: "I've studied [X] of [entities] that [achieved outcome] successfully.", author: "Matt Gray" },
  { text: "Here's how to get ahead of [X]% of people:", author: "Matt Gray" },
  { text: "Here's what it really takes to build a $[X] [asset]", author: "Matt Gray" },
  { text: "Earlier this [timeframe], my [role] gave me a(n) [exercise/insight] I haven't stopped thinking about.", author: "Matt Gray" },
  { text: "Most [role] drift through [timeframe] with no [structure/rhythm].", author: "Matt Gray" },
  { text: "How to set a [asset] you'll actually use:", author: "Matt Gray" },
  { text: "[X] reasons why you should start a(n) [venture] today:", author: "Matt Gray" },

  { text: "Every business wants to align [department A] and [department B]. But most of them fall into this ONE trap: [misconception].", author: "Pierre Herubel" },
  { text: "Here's what you don't need to start [activity]: [list]. Here's what you need to start [activity]: [list].", author: "Pierre Herubel" },
  { text: "\"[Role]: '[question]'\" Me: \"First, you need to answer these [X] questions:\"", author: "Pierre Herubel" },
  { text: "One [recorded input] = [X] [timeframe] of [output].", author: "Pierre Herubel" },
  { text: "Too many [entities] line up [actions] on a [tool] and call it \"[label]\".", author: "Pierre Herubel" },
  { text: "\"[Common belief]\" Good in theory, but here are [X] problems:", author: "Pierre Herubel" },
  { text: "I talk with a lot of [role] who: [positive traits]. But still struggle to [desired outcome].", author: "Pierre Herubel" },
  { text: "I wrote about [concept] in [past date]. I spotted [X] problems that are even more obvious today:", author: "Pierre Herubel" },
  { text: "I've audited over [X] [assets]. My advice: ask yourself THIS question: \"[diagnostic question]\"", author: "Pierre Herubel" },
  { text: "\"[Role]: '[complaint]'\" Me: \"It could come from those [X] problems:\"", author: "Pierre Herubel" },
  { text: "\"[Urgent demand]\" These expectations come from one false belief: [misconception].", author: "Pierre Herubel" },
  { text: "My [asset] just hit [X] [metric]. [Y] rules I wish I knew when I started in [year]:", author: "Pierre Herubel" },
  { text: "\"[Role]: 'I want to [goal].'\" Me: \"Here are [X] aspects you should work on:\"", author: "Pierre Herubel" },
  { text: "[Content type] is the best [audience] tactic for [year].", author: "Pierre Herubel" },
  { text: "The best [role] know these [X] principles:", author: "Pierre Herubel" },
  { text: "This question will shape your [category] strategy in [year]: (It impacts your [A], [B], and [C]) \"[strategic binary-choice question]\"", author: "Pierre Herubel" },
  { text: "In [year], a new breed of [entity] is rising:", author: "Pierre Herubel" },
  { text: "Most [entities] reinvent their [asset] every [timeframe]:", author: "Pierre Herubel" },
  { text: "In [year], your [asset] needs [component].", author: "Pierre Herubel" },
  { text: "\"[Role]: 'We don't get ROI from [asset]'.\" Me: \"Do you run this [system]?\"", author: "Pierre Herubel" },
  { text: "I've invested over [X] hours in [skill/domain].", author: "Pierre Herubel" },
  { text: "A lot of [role] are starting [activity] in [year]. Most of them fall straight into the \"[trap name]\":", author: "Pierre Herubel" },
  { text: "I've analyzed over [X] [asset] strategies.", author: "Pierre Herubel" },
  { text: "I've helped over [X] [entities] fix their [asset].", author: "Pierre Herubel" },
  { text: "In [year], many [role] still confuse [concept A] and [concept B]:", author: "Pierre Herubel" },
  { text: "Biggest mistake I see in [category] strategy: (Read this to [desired outcome] in [year])", author: "Pierre Herubel" },
  { text: "I've seen hundreds of ambitious [asset] plans:", author: "Pierre Herubel" },
  { text: "My new [offer] starts [timeframe]. Here are [X] updated rules I'm going to teach:", author: "Pierre Herubel" },
  { text: "I'm curious to know, are you [doing trend action] with [tool]?", author: "Pierre Herubel" },
  { text: "\"[Role]: 'We struggle to organize [category] efforts.'\" Me: \"Here's the 1st fix to structure your day-to-day:\"", author: "Pierre Herubel" },
  { text: "In [year], [asset A] becomes a(n) [asset B]: (And this shift will impact your [category] strategy)", author: "Pierre Herubel" },
  { text: "I've audited [X]+ [asset] strategies. Most of them skipped this crucial rule:", author: "Pierre Herubel" },
  { text: "It's early [year], you're planning your [category] strategy. This crucial decision should be on your radar: \"[strategic question]\"", author: "Pierre Herubel" },
  { text: "🎉 My new [offer] starts in [month]! You'll learn my [X]-step system behind [Y] [metric]:", author: "Pierre Herubel" },
  { text: "- Domino 1: [X] ... That's the \"[chain-effect name]\".", author: "Pierre Herubel" },
  { text: "In [year], too many [entities] still start from \"[shortcut action]\". Here are the [X] strategic layers they're missing:", author: "Pierre Herubel" },
  { text: "The [category] playbook changed a lot in [X] years. Here are the [Y] biggest tactical shifts:", author: "Pierre Herubel" },
  { text: "\"[Role]: 'What's the 1st step for a good [category] strategy?'\" Me: \"Avoid these [X] [category] mistakes:\"", author: "Pierre Herubel" },
  { text: "Many [role] want \"[desired outcome]\" as fast as possible.", author: "Pierre Herubel" },
  { text: "My last [X] posts got saved [Y] times.", author: "Pierre Herubel" },
  { text: "The [X]-step [system name] for [year]: (Most [role] skip step [N] and [M])", author: "Pierre Herubel" },
  { text: "In [year], best [entities] mix [approach A] and [approach B] [category].", author: "Pierre Herubel" },
  { text: "This is the winning [category] playbook for [year]. Let me break it down for you with [X] pillars:", author: "Pierre Herubel" },
  { text: "I'm interested to know what's your [focus type] for [year]", author: "Pierre Herubel" },
  { text: "[Category] are changing in [year]. Here's the new playbook explained in [X] parts:", author: "Pierre Herubel" },
  { text: "Here's your [X]-week [asset] plan: (to kick off [year] with a clear roadmap)", author: "Pierre Herubel" },
  { text: "\"[Role]: 'What should I focus on in [year]?'\" Me: \"Start with my [X] mandatory rules:\"", author: "Pierre Herubel" },
  { text: "[Year]: time to build your [system name].", author: "Pierre Herubel" },
  { text: "Many [role] think [category A] & [category B] [domain] are \"similar\". But there is one BIG difference that changes everything:", author: "Pierre Herubel" },
  { text: "The worst [category] scenario for [role]:", author: "Pierre Herubel" },
  { text: "I've trained [X]+ [role] to [skill]. Most struggled with the SAME [problem type] problem:", author: "Pierre Herubel" },
  { text: "Most [entities] neglect [category]:", author: "Pierre Herubel" },

  { text: "This is how I've grown to [X]+ [metric] on [platform].", author: "Lara Acosta" },
  { text: "I've written over [X]+ viral [platform] [content type].", author: "Lara Acosta" },
  { text: "My [platform] [asset] has made me $[X]+ this [timeframe].", author: "Lara Acosta" },
  { text: "I have [X] followers on [platform].", author: "Lara Acosta" },
  { text: "I've built [X]x $[Y]+ [metric] [asset] using [Z] rule(s):", author: "Lara Acosta" },
  { text: "My business made $[X] in [timeframe].", author: "Lara Acosta" },
  { text: "I've bootstrapped [X] [assets] from $[Y]-[Z]+. It's taken me [timeframe] and [effort unit], but it all came down to [N] key pillars that guarantee [outcome]. Here's the breakdown:", author: "Lara Acosta" },
  { text: "[Name] has [X] followers.", author: "Lara Acosta" },
  { text: "I have [name] in my corner as a [role].", author: "Lara Acosta" },
  { text: "Some people show up. [Name] shows out.", author: "Lara Acosta" },
  { text: "Intro for the latest [deliverable] we [made] for [client/name]", author: "Lara Acosta" },
  { text: "I asked someone with [X]+ [platform] followers how to [desired outcome].", author: "Lara Acosta" },
  { text: "I finally met my favorite [platform] [role] in real life.", author: "Lara Acosta" },
  { text: "Last [time period A], nobody knew my damn name. Last [time period B], [name] invited me to [their] [event] in [location]:", author: "Lara Acosta" },
  { text: "[Announcement] is coming..", author: "Lara Acosta" },
  { text: "POV: Your [event] goes viral and breaks records.", author: "Lara Acosta" },
  { text: "Yes, [this/that] just happened 👇", author: "Lara Acosta" },
  { text: "Big [category] news today!", author: "Lara Acosta" },
  { text: "Woke up to seeing my [asset] featured in [publication]!!", author: "Lara Acosta" },
  { text: "The BEST [category], [month] [year]. ↴", author: "Lara Acosta" },
  { text: "FINAL CALL", author: "Lara Acosta" },
  { text: "My [X]-step [platform] [skill] framework is unbeatable.", author: "Lara Acosta" },
  { text: "The cheat code to [outcome] is [trait/input].", author: "Lara Acosta" },
  { text: "The fastest way to [desired outcome] isn't through [common assumed tactic]", author: "Lara Acosta" },
  { text: "Most people on [platform] are looking for [decoy solution].", author: "Lara Acosta" },
  { text: "There's no such thing as [impossible claim].", author: "Lara Acosta" },
  { text: "This is the [category] hack [role] use on [platform].", author: "Lara Acosta" },
  { text: "The best [platform] [asset] has ZERO [funding type].", author: "Lara Acosta" },
  { text: "This [place/thing] saved me.", author: "Lara Acosta" },
  { text: "I hadn't seen my [people] in [timeframe].", author: "Lara Acosta" },
  { text: "If you've ever felt like you wanted to [give up action], read this:", author: "Lara Acosta" },
  { text: "I used to think [X] was \"[assumed trait]\". Now all I see is [contradicting reality].", author: "Lara Acosta" },
  { text: "If I had to grow my [asset] to [X] all over again...", author: "Lara Acosta" },
  { text: "I went offline for [timeframe], but returned to see my [asset] ALL OVER the [platform] feed…", author: "Lara Acosta" },
  { text: "[Month] has been a monumental [timeframe] for my [asset].", author: "Lara Acosta" },
  { text: "[Time period] ago, I didn't think any of this was possible.", author: "Lara Acosta" },
  { text: "[Time period] ago my WHOLE [life area] changed....", author: "Lara Acosta" },
  { text: "[Date] was one of the best days of my [life area].", author: "Lara Acosta" },
  { text: "This feels unreal. We broke every record on [platform].", author: "Lara Acosta" },
  { text: "I can't believe our [channel] looks like this right now.", author: "Lara Acosta" },

  { text: "I've grown from [0-X] followers on [platform].", author: "Lara Acosta" },
  { text: "There's [X]s of ways to get more [metric] on [platform].", author: "Lara Acosta" },
  { text: "I grew my [platform] to [X] followers using this [Y] trick(s).", author: "Lara Acosta" },
  { text: "From [X] [metric] to [Y], to more than [Z], within [timeframe]. So, [name] invited me for the [Nth] time to speak at [their] live [event type]", author: "Lara Acosta" },
  { text: "I've spent [X]+ years analysing viral [platform] [content type].", author: "Lara Acosta" },
  { text: "This is [name], we met at a [place] in [month].", author: "Lara Acosta" },
  { text: "[Name], [role 1], [role 2], and the number [X] [demographic] creator on [platform].", author: "Lara Acosta" },
  { text: "[She/He/They] built [X] followers on [skill]. I couldn't crack [Y] even as a literal [related expert role].", author: "Lara Acosta" },
  { text: "I just booked flights to [location] for a few [product] users.", author: "Lara Acosta" },
  { text: "I (finally) landed a 1:1 [meeting type] with the [platform/company] team.", author: "Lara Acosta" },
  { text: "And I said yes before I even finished [reading/hearing] the [message/offer].", author: "Lara Acosta" },
  { text: "We got talking about [topic 1], [topic 2], and what we're building.", author: "Lara Acosta" },
  { text: "pov: [X]hrs in [location] during launch week for our viral [industry] [asset] (i can't believe this is happening)!", author: "Lara Acosta" },
  { text: "pov: you're building a [status]-figure [industry] [asset] on [platform] with [people] in your [age range] (bts of a $[X]+ [asset]).", author: "Lara Acosta" },
  { text: "BIG NEWS: We're relaunching [product] in [X] days.", author: "Lara Acosta" },
  { text: "Huge announcement... We're launching [product] [version] (live).", author: "Lara Acosta" },
  { text: "I'm doing it. I'm hosting my first in-person [location] [event type].", author: "Lara Acosta" },
  { text: "My [client/student] got [X]+ [metric] on [platform] (and [secondary outcome])!!", author: "Lara Acosta" },
  { text: "I made $[X] in [Y] days with this [business model] system.", author: "Lara Acosta" },
  { text: "I built a $[X]+ [metric] [asset] with these non-negotiables.", author: "Lara Acosta" },
  { text: "This \"[simple]\" strategy built my first [X]-fig [asset].", author: "Lara Acosta" },
  { text: "I spent the last [X] days breaking down how to build a $[Y]/mo [asset] system on [platform].", author: "Lara Acosta" },
  { text: "The secret to [outcome] on [platform] (and [broader category]):", author: "Lara Acosta" },
  { text: "A stupid simple way to [start/achieve goal]:", author: "Lara Acosta" },
  { text: "Don't [common action] in a [flat/undesirable adjective], [adjective] way.", author: "Lara Acosta" },
  { text: "If you're a [identity/niche], this is your sign to start [building asset].", author: "Lara Acosta" },
  { text: "I nearly quit [platform] [timeframe].", author: "Lara Acosta" },
  { text: "[X] years ago I left EVERYTHING behind 👀", author: "Lara Acosta" },
  { text: "Just [X] years ago:", author: "Lara Acosta" },
  { text: "[X] years ago, I was trying to figure out [skill/topic].", author: "Lara Acosta" },
  { text: "[X] years ago my [asset/strategy] was [negative descriptor].", author: "Lara Acosta" },
  { text: "I look [adjective] on [context], but I felt like [an imposter/negative feeling] all day...", author: "Lara Acosta" },
  { text: "I read a comment that said my \"[asset] is too [criticism]\".", author: "Lara Acosta" },
  { text: "Every single [timeframe], I see a [content type] celebrating my [outcome].", author: "Lara Acosta" },
  { text: "If you want more [metric] on your [platform] [content type]..", author: "Lara Acosta" },
  { text: "If you've been struggling with [problem]... this is for you.", author: "Lara Acosta" },
  { text: "If you feel like [platform] isn't working for you this is why:", author: "Lara Acosta" },

  { text: "I ran into the number [X] [platform] [role] on the planet.", author: "Lara Acosta" },
  { text: "Everyone says you should [common advice] your [target].", author: "Lara Acosta" },
  { text: "The best [category] advice I can give you this [year]:", author: "Lara Acosta" },
  { text: "\"Me failing at [context] meant me failing [them] too.\"", author: "Lara Acosta" },
  { text: "This is by far the most [adjective] thing about my [role/job].", author: "Lara Acosta" },
  { text: "This is for everyone who thinks they need [resource] to [scale/achieve outcome] their [asset].", author: "Lara Acosta" },
  { text: "I'm leaking my [personal contact/asset].", author: "Lara Acosta" },
  { text: "Don't chase [decoy target].", author: "Lara Acosta" },
  { text: "You have no [assumed requirement].", author: "Lara Acosta" },
  { text: "I just went on [name]'s [show type] and shared some of my best [skill] & [skill 2] playbooks… including:", author: "Lara Acosta" },
  { text: "If you're not building a(n) [trend] [category] right now, what are you doing?", author: "Lara Acosta" },
  { text: "Last [timeframe], [name] and I decided to [change/impact] a few [people/lives].", author: "Lara Acosta" },
  { text: "They say don't meet your heroes. Then I had [interaction] with [name].", author: "Lara Acosta" },

  { text: "Over the last [X] years I've worked 1-1 with [Y]+ [role] to [outcome]. Here's the single biggest problem they had:", author: "Matt Barker" },
  { text: "Nerdy confession: for [X] years I've [habitual action]. And I've been [doing related thing] for the last [Y] [timeframe]. But... Here's my all-time record.", author: "Matt Barker" },
  { text: "I've personally closed $[X] since [date] for my own [offer]. If you're a [role] and your [tactic] is starting to work less and less, try this:", author: "Matt Barker" },
  { text: "I've worked with [X]+ [role] over the last [Y] years with their [category] strategy. On [day] I kicked off with a new client who has [Z] followers on [platform], but:", author: "Matt Barker" },
  { text: "Over the last [X] years I've helped [Y]+ of the smartest [role] [achieve outcomes]: [names]. If you could ask me anything about the work I do with my clients, what would you ask?", author: "Matt Barker" },
  { text: "Honestly, this was me before I started my own business in [year]. And it's (partly) why I get DMs from [roles] asking to [desired outcome].", author: "Matt Barker" },
  { text: "Over the last [X] weeks I've been working 1-1 with a [role] to [goal]. He has [Y] [platform] followers and [Z] of experience in his industry. But outside that, starting from scratch:", author: "Matt Barker" },
  { text: "A new app idea called [pun name] where people can post about how they replaced their entire [department] with [tool].", author: "Matt Barker" },
  { text: "Smart people writing a [content type] in [year A]: [list]. The same people writing a [content type] in [year B]: [list].", author: "Matt Barker" },
  { text: "Day in the life of a [age] [role] in [location] (with a [family detail]):", author: "Matt Barker" },
  { text: "I've advised over [X] [role] on their [category] strategy. The first thing I tell them is to [advice]. Here's what I ACTUALLY mean by that:", author: "Matt Barker" },
  { text: "Until [year], I was firmly on the [safe/gold] line here.", author: "Matt Barker" },
  { text: "Everyone's decided [category] is finished because [trend/tech] can [replace it]. But it's the wrong conclusion.", author: "Matt Barker" },
  { text: "When did you last ask your [audience asset] if they wanted to [desired action]?", author: "Matt Barker" },
  { text: "Last week I was flying from [location A] back to [location B] and spotted this funny looking [item]. I bought it for my [family member]. But, WHAT on EARTH:", author: "Matt Barker" },
  { text: "I could write [content type] for the next [X] years. Non stop. But if I was struggling to find ideas to [do task] on a daily basis, I would NOT do this:", author: "Matt Barker" },
  { text: "My hottest [category] tip of [year]:", author: "Matt Barker" },
  { text: "In [year], I've [done action] [X] times on [platform]. I know, WTF. Crazy? What's crazier is I've never sat down and thought: \"[common question]\"", author: "Matt Barker" },
  { text: "Yesterday I was chatting to a(n) [role] doing $[X]+/[timeframe]. He wants to [goal]. But he's currently making [Y] mistakes:", author: "Matt Barker" },
  { text: "[He/She] told me [they] [achieved small outcome]. But [they] lied to me: [They] [achieved bigger outcome] :)", author: "Matt Barker" },
  { text: "I open like [X]% of my [content type A] and [content type B] with the same, formulaic sentence.", author: "Matt Barker" },
  { text: "I just spent the last [X] weeks in [location A] and now we're heading back to [location B]! It's been a wonderful [trip/period]:", author: "Matt Barker" },
  { text: "The best test I know for a [content type] takes about [X] seconds.", author: "Matt Barker" },
  { text: "I've closed around $[X] for my [business type] over the last [Y] years. But not one lead has ever said \"[unrealistic quick-win quote]\".", author: "Matt Barker" },
  { text: "Do you want to [desired outcome A] and ultimately [desired outcome B] with the [asset] you make? And you don't want to [decoy tactic] or just [shallow metric] for [shallow metric]'s sake?", author: "Matt Barker" },
  { text: "If you sit down to [task] and can't think of anything, the problem isn't that your [life/input] is boring.", author: "Matt Barker" },
  { text: "A few weeks after [getting a personal item/commitment], I still can't stop [reaction]. Best [money/decision] I've ever [spent/made].", author: "Matt Barker" },
  { text: "I'm [age] years old. I run a one person, multi [X] figure/year [business type]. But when something's weighing on me, there's NO debate who I tell first (hint, it's not a [decoy]):", author: "Matt Barker" },
  { text: "I grew to [X] followers in my first [Y] months. You could say I got lucky. You'd be [Z]% right, because:", author: "Matt Barker" },
  { text: "I DID IT. I completed my [X] day [content type] experiment where I only [create asset] that:", author: "Matt Barker" },
  { text: "I've no idea if this will work or who this will even find but I'm gonna make a random, free offer today based on something I keep seeing on the [platform] feed.", author: "Matt Barker" },
  { text: "In [year A], I was earning £[X] as a [role]. But in [year B], a brand paid me £[Y] for [Z] sponsored [content type] posts.", author: "Matt Barker" },
  { text: "I'm [age] years old today. I know, you'd never guess. But here's the [sad/funny] bit:", author: "Matt Barker" },
  { text: "WTF. My [family member] told me I'm [criticism]. I'm [X] years into running a [business type], done $[Y]+ revenue. But as always:", author: "Matt Barker" },
  { text: "I'm not convinced about \"[common industry advice].\"", author: "Matt Barker" },
  { text: "I posted [X] times on [platform] in the last [Y] [timeframe]. But only [Z] were \"[winners label]\".", author: "Matt Barker" },
  { text: "I COULD be making $[X]/year. But I deliberately make less. Yes idiot, I know, but here's my reason:", author: "Matt Barker" },
  { text: "In the last [X] days, my [client type] had [platform] posts hit [Y] likes and [Z] likes. But he \"only\" has [W] followers. Weird, init?", author: "Matt Barker" },
  { text: "You can be worth $[X]+ but STILL get ignored on [platform].", author: "Matt Barker" },
  { text: "I've written [X]+ [platform] posts. But the real skill isn't [obvious skill], it's:", author: "Matt Barker" },
  { text: "Last [season], I mentored a well known [platform] [role] with [X] followers. But he was already [doing core task] and:", author: "Matt Barker" },
  { text: "In the last [X] days, I've seen [Y] [platform] [role] with under [Z] followers have breakout [platform] posts:", author: "Matt Barker" },
  { text: "Last week I abandoned my [X] day [content type] experiment because I was busy doing something the [industry] gurus HATE:", author: "Matt Barker" },
  { text: "Last [day], I started a [X] day [platform] post experiment. But with [Y] (kinda) strict rules:", author: "Matt Barker" },
  { text: "Last week was fun for my [business type]:", author: "Matt Barker" },
  { text: "[X] years ago I started posting on [platform]. I got mocked every week for it in [context]. But after about [Y] months:", author: "Matt Barker" },
  { text: "If I ever feel lost in my: [list of life/business areas]. The worst I can do is [decoy behavior].", author: "Matt Barker" },
  { text: "My [family member] is [age]. I desperately want to [priority], not: [decoy time-sink].", author: "Matt Barker" },
  { text: "In [month], I wrote a [content type] with a [X] word hook. The first line was boring. But the second line broke all the \"rules\" and the post went nuts. Full breakdown below (you'll wanna save this):", author: "Matt Barker" },
  { text: "[Year] is just NUTS. Last week, I: [list]", author: "Matt Barker" },
  { text: "I've grown my [platform] profile to [X] followers in [Y] years. If I had to start from 0 again, here's one piece of advice I'd like to hear:", author: "Matt Barker" },
  { text: "I've noticed the [platform] feed has become more like [Platform A] or [Platform B].", author: "Matt Barker" },
  { text: "This is [Famous Person]. [They're] one of the most famous [role] in the world. [X] [platform] followers. But even if me and [them] had 0 followers:", author: "Matt Barker" },
  { text: "Last week I reviewed a(n) [role]'s [platform] post. He has [X] followers. The post got [Y]+ likes. But here's what his post opened with:", author: "Matt Barker" },
  { text: "I'll admit, I am a sucker for a [genre]. [Title] is a classic IMO. [Reaction]. But it's the same story as every [genre] from the last [X] years:", author: "Matt Barker" },
  { text: "I absolutely hate this [platform] advice: \"[quoted bad advice]\"", author: "Matt Barker" },
  { text: "Last week I wrote a [content type] for my [client role] that currently has...*checks analytics*...[X] likes and [Y] impressions.", author: "Matt Barker" },
  { text: "I've earned myself [X] impressions on [platform] in the last [Y] months. [Z] posts. I'm a psycho for posting that much. But here's [N] alternative ways to approach writing your next [content type]:", author: "Matt Barker" },
  { text: "I know it seems impossible but: It IS possible to enjoy [disliked task].", author: "Matt Barker" },
  { text: "Admit it. You're using [tool] to 'fix' your [content type] 🍻", author: "Matt Barker" },
  { text: "People of [platform]. Settle a petty debate for me:", author: "Matt Barker" },
  { text: "You wrote a [content type] you were SURE was great. You posted it. Then you watched: As it got [X] impressions, [Y] like and [Z] comments.", author: "Matt Barker" },
  { text: "I've learned this about [skill] after [X] [platform] posts:", author: "Matt Barker" },
  { text: "My best tip if you MUST use [tool] to write [content type]:", author: "Matt Barker" },
  { text: "The [platform] experts told people to [common advice] as hard as possible.", author: "Matt Barker" },
  { text: "[Platform] has a new [role]. And there's never been a clearer, more obvious clue of what [platform] wants to be (and is) all about:", author: "Matt Barker" },
  { text: "About a week ago, I had a post that got: [stats]. The next post I put out only got: [stats].", author: "Matt Barker" },
  { text: "[Tool] won't fix your [content type]'s \"[quality trait]\" unless: You know what a good \"[quality trait]\" is.", author: "Matt Barker" },
  { text: "The biggest [metric] arbitrage on [platform] in the [niche] niche RIGHT NOW is: [trend].", author: "Matt Barker" },
  { text: "I've wasted [X] years of my life [doing habitual thing]. (and it didn't make me a single penny)", author: "Matt Barker" },
  { text: "You asked [tool] how to format your [content type]. It told you: [advice list]", author: "Matt Barker" },
  { text: "[X] years ago I started a [business type].", author: "Matt Barker" },
  { text: "If you need extreme [behavior] just to feel \"okay\": You're in the wrong [category].", author: "Matt Barker" },
  { text: "People are still spending [X] hours [doing tactic].", author: "Matt Barker" },
  { text: "[X] years ago, I launched my first [product type]. I gave [Y]% of it away for free. Seems dumb I know. But here's how it got me [Z] [audience asset] and made $[W]+ every month:", author: "Matt Barker" },
  { text: "My goals for life don't include hitting $[X] [metric].", author: "Matt Barker" },
  { text: "Everyone tells you to write like this: [Formatting style example].", author: "Matt Barker" },
  { text: "Sorry but what the hell has [platform] done to [feature]?", author: "Matt Barker" },
  { text: "[Platform] advice has been the same since I started posting in [year].", author: "Matt Barker" },
  { text: "[Platform]'s algo is on fire. I've got posts from [X] months ago still getting engagement.", author: "Matt Barker" },
  { text: "\"[Common myth].\" I've heard this for years and it's complete BS.", author: "Matt Barker" },
  { text: "[X] minutes. That's how long it took a [client role] to write a [content type] that drove $[Y] in [outcome].", author: "Matt Barker" },
  { text: "Shout out to everyone [doing task] with less than [X] [metric] and no [outcome].", author: "Matt Barker" },
  { text: "[Name], this is [Platform]. It has [X] members, has made thousands of people [outcome]... Its only defect is that [ironic complaint].", author: "Matt Barker" },
  { text: "I say and do [negative thing] every week. I also say and do [positive thing] every week. But if you notice, the ones who don't have anything to look back at and say \"[self-deprecating phrase]\" are the ones who either:", author: "Matt Barker" },
  { text: "This pic is me, [month/year]. I'd been [doing habitual action] every single day for [X] weeks. I got zero [metric]. My [family member] asked me why I kept doing it, and:", author: "Matt Barker" },
  { text: "It is with a heavy heart that I am forced to address the [malicious] allegations that have been circulating on this platform.", author: "Matt Barker" },
  { text: "[Relation] of mine is currently [going through hardship]. He's going through a rough time of it and asked if I've ever [had similar experience] and how I navigated through [it].", author: "Matt Barker" },
  { text: "I DO NOT want to be a famous [aspirational label].", author: "Matt Barker" },
  { text: "Andddddd we have a [baby/announcement]! [emoji]", author: "Matt Barker" },
  { text: "I wrote [X] hooks for my [content type] in [year]. Save yourself months of [pain point] and copy my process instead:", author: "Matt Barker" },
  { text: "I've posted for [X] years straight on this beautiful hell hole we call [platform]. Here's what I would've paid $[Y] to know before I started:", author: "Matt Barker" },
  { text: "I'll be honest. Some [tool]-written [content type] are so good now, I can't tell it was written by [tool].", author: "Matt Barker" },
  { text: "You'll hate reading this. But last year, I: [list of stats]", author: "Matt Barker" },
  { text: "How to GUARANTEE a '[bad outcome]' [category]:", author: "Matt Barker" },
  { text: "On bad [days/times], just do ONE [thing]. ONE. that's it.", author: "Matt Barker" },
  { text: "How to (finally) be confident [doing task]:", author: "Matt Barker" },
  { text: "My first [content type] = total flop. Why? One reason:", author: "Matt Barker" },
  { text: "The short answer is [no/yes].", author: "Matt Barker" },
  { text: "[X] things I've posted on [platform] in the last [Y] days:", author: "Matt Barker" },
  { text: "Read this, and you'll never ask again: \"[Common Question]\"", author: "Matt Barker" },
  { text: "I hate to say this. But the odds of: [list]", author: "Matt Barker" },
  { text: "I average roughly [X]-[Y]k impressions per [content type]. But last week THIS post flopped. [Z] random thoughts on why:", author: "Matt Barker" },
  { text: "I've got terrible news. If you don't: [list]", author: "Matt Barker" },
  { text: "[X] ridiculous ways my life has changed since I wrote my first [content type]:", author: "Matt Barker" },
  { text: "This [role] I'm coaching just wrote their biggest [content type] of the year 🤘 A normal post for them gets [X]-[Y] likes. This one got [Z]. Here's what we did:", author: "Matt Barker" },
  { text: "Last week I had a BAD time [doing task]: (read this to feel better about your [category] woes lol)", author: "Matt Barker" },
  { text: "I've [done activity] on [platform] since [date] and yes, the game has changed. For the better or worse? Depends how you look at it. But I used to:", author: "Matt Barker" },
  { text: "I have one strict rule for writing [content type] hooks. (been ruthless with my clients on this in [year A] & '[year B])", author: "Matt Barker" },
  { text: "I already wrote a [Holiday] post today but i deleted it because i hated it.", author: "Matt Barker" },
  { text: "When I was [age] years old, I started [precocious business behavior].", author: "Matt Barker" },
  { text: "[Platform] [Category] Reminder #[X]: Last week I had a post hit [Y]k impressions. The next day my post hit [Z]k impressions.", author: "Matt Barker" },
  { text: "You don't have a [decoy] problem: You have a [real] problem.", author: "Matt Barker" },
  { text: "I've struggled to: [list of struggles]", author: "Matt Barker" },
  { text: "[X] years ago, my [family member] asked me \"[pointed question]\".", author: "Matt Barker" },
  { text: "[X] weeks ago my [client role] client had NEVER [done task]. NEVER. But that didn't stop him from:", author: "Matt Barker" },

  { text: "My [asset/skill] is the best on earth. YEAH I SAID IT.", author: "Dan James" },
  { text: "I would rather do a backflip into an active volcano than [do disliked mediocre thing].", author: "Dan James" },
  { text: "[Category] has become so bad in [year], people should be fined for each [unit] they send.", author: "Dan James" },
  { text: "I DESPISE [tactic/thing].", author: "Dan James" },
  { text: "Give me [X] years in a maximum security prison before sending a '[cliché phrase]' message.", author: "Dan James" },
  { text: "Drink bleach or [do disliked mediocre thing] as everyone else? Please, pass the chlorox sir.", author: "Dan James" },

  { text: "[Name] got a $[X]k job offer using [this/my] [Product Name].", author: "Anna Chernyshova" },
  { text: "[Name] got [X] job interviews and landed a [role type] at [his/her] dream company using [my] [Product Name].", author: "Anna Chernyshova" },
  { text: "You are not getting rejected because you lack skills. You are rejected because of what you say in [context].", author: "Anna Chernyshova" },
  { text: "[He/She] got ghosted after [X] rounds of interviews.", author: "Anna Chernyshova" },
  { text: "You will get rejected a LOT. Here is what to do if you get rejected:", author: "Anna Chernyshova" },
  { text: "[X] Must-Ask Questions during your [event]. And why they are important.", author: "Anna Chernyshova" },
  { text: "I've interviewed over [X] candidates. The most prepared candidates get the [outcome].", author: "Anna Chernyshova" },
  { text: "[Doing hard thing while unwell] isn't loyalty. It's a sign of a toxic [culture type].", author: "Anna Chernyshova" },
  { text: "A SECRET [role] don't want you to know. You should be a [contrarian strategy].", author: "Anna Chernyshova" },
  { text: "People don't care about [surface perks]. They care about: [list]", author: "Anna Chernyshova" },
  { text: "A [positive role] makes people feel [positive state]. A [negative role] makes people feel [negative state].", author: "Anna Chernyshova" },
  { text: "My clients on average negotiate [X]% higher [outcome].", author: "Anna Chernyshova" },
  { text: "[Trend] has made the [market] extremely competitive in [year].", author: "Anna Chernyshova" },
  { text: "[X] things you MUST do to secure a [outcome] in this tough [market]:", author: "Anna Chernyshova" },
  { text: "My candidate got a $[X]k job offer with [interview prep/tactic].", author: "Anna Chernyshova" },
  { text: "My candidate got a [X]-figure job offer this week. Answer these [Y] questions strategically.", author: "Anna Chernyshova" },
  { text: "I've interviewed over [X] candidates. Here are [Y] things you should NEVER say in a [event]: Some of the most qualified people talk themselves out of a [outcome].", author: "Anna Chernyshova" },
  { text: "Your [credential] does NOT make you a [role]. Here are [X] traits that do 👇", author: "Anna Chernyshova" },
  { text: "I interviewed over [X] candidates for a job. Here are [Y] things you need [to do/say] to impress the [decision maker].", author: "Anna Chernyshova" },
  { text: "[X]% of [role] leave their jobs because of [cause] ([Source]). There's no such thing as \"bad\" [things]. There are bad [true cause].", author: "Anna Chernyshova" },
  { text: "Most [role] think [common belief]. It's not. There are \"invisible rules\" that [decision makers] evaluate that most [role] never realize.", author: "Anna Chernyshova" },
  { text: "Most people think [task] takes [long timeframe]. It doesn't. You can do it in [short timeframe].", author: "Anna Chernyshova" },
  { text: "\"[Quote]\" - [Author Name]", author: "Anna Chernyshova" },
  { text: "I interviewed over [X] candidates. Here are [Y] things you MUST include on your [asset] to stand out (and why they are important).", author: "Anna Chernyshova" },
  { text: "Before [doing common action], [do alternative action].", author: "Anna Chernyshova" },
  { text: "I reviewed [X]+ [assets]. Most [role] think [assumption]. They're not. [Decision makers] spend about [Y] seconds on each [asset].", author: "Anna Chernyshova" },
  { text: "Another candidate got a [X]-figure job offer. Most [role] don't get rejected because they lack [skill]. They get rejected because of how they [answer/perform].", author: "Anna Chernyshova" },
  { text: "[Category] should ONLY ask for [X] things: [list]", author: "Anna Chernyshova" },
  { text: "[Decision makers] think you're lying. Here is how to optimize your [asset] to stand out:", author: "Anna Chernyshova" },
  { text: "One of the biggest mistakes [role] make: Ignoring [warning signs] during the [process].", author: "Anna Chernyshova" },
  { text: "Most [role] think they got rejected because they were \"[assumed reason].\" But most of the time… the signs were already there during the [process].", author: "Anna Chernyshova" },
  { text: "Comment below \"[word]\" if you've been [experienced negative thing].", author: "Anna Chernyshova" },
  { text: "No one [does common thing] anymore. Instead, focus on [alternative things].", author: "Anna Chernyshova" },
  { text: "[Role] should not have to complete [X] [rounds] for one [outcome].", author: "Anna Chernyshova" },
  { text: "How we treat [group] is everything.", author: "Anna Chernyshova" },
  { text: "People don't leave [thing]. They leave [true cause].", author: "Anna Chernyshova" },
  { text: "That [thing] you've been waiting for so long. It's coming your way.", author: "Anna Chernyshova" },
  { text: "[Positive intervention] won't fix a broken [culture/system].", author: "Anna Chernyshova" },
  { text: "If you already know you are hiring a(n) [internal candidate], please do not [post/do] the [process] externally.", author: "Anna Chernyshova" },
  { text: "I have interviewed over [X] candidates for a job. Here is how to answer difficult [category] questions.", author: "Anna Chernyshova" },
  { text: "When you [reward/promote] toxic [people], you will lose your best [people].", author: "Anna Chernyshova" },
  { text: "It's CRAZY people are still NOT doing [this/specific action].", author: "Anna Chernyshova" },
  { text: "First sign you should quit your [job/situation]", author: "Anna Chernyshova" },
  { text: "Some [decision makers] decide too slowly.", author: "Anna Chernyshova" },
  { text: "[Category] ask for too much.", author: "Anna Chernyshova" },
  { text: "Most [role] walk into [event] trying to prove they're [trait]. Strong [role] do something different.", author: "Anna Chernyshova" },
  { text: "[Role] should know the [key info] before the first [event].", author: "Anna Chernyshova" },
  { text: "We made an offer to the [role] after the FIRST [event].", author: "Anna Chernyshova" },
  { text: "The [decision maker] knows when you use [tool] to write your [asset].", author: "Anna Chernyshova" },
  { text: "This is the biggest mistake you make in [event]: You [common error].", author: "Anna Chernyshova" },
  { text: "The gap between [state A] and [state B] is smaller than you think (and it's fixable).", author: "Anna Chernyshova" },
  { text: "You've interviewed [X] candidates and no hire? YOU are the problem.", author: "Anna Chernyshova" },
  { text: "You keep getting rejected from [category] because of this.", author: "Anna Chernyshova" },
  { text: "[Factor] is one of the biggest factors in [decision type]. You can have the right [qualification]. But if the [decision maker] doesn't [trust] you, you won't get the [outcome].", author: "Anna Chernyshova" },
  { text: "I've coached [X]+ [role] into multiple [outcome]. Here's what [decision makers] actually respond to in your [asset].", author: "Anna Chernyshova" },
  { text: "I've coached over [X] [role] land multiple [outcome]. Toxic [people] will cost you a lot more than just a [thing].", author: "Anna Chernyshova" },
  { text: "There is nothing worse than starting a new [thing] and realizing you should have never accepted [it].", author: "Anna Chernyshova" },
  { text: "I've interviewed over [X] candidates. And this is why qualified [role] aren't getting [outcome]. 👇", author: "Anna Chernyshova" },
  { text: "[X]% of [outcomes] are filled through [method]. Here is how to turn [platform] [method] into [outcome].", author: "Anna Chernyshova" },
  { text: "[X] years of [role] taught me one thing: Most [role] are vulnerable and don't even know it.", author: "Anna Chernyshova" },
  { text: "I've worked with [X]+ [decision makers]. Here are [Y] mistakes killing your [event] 👇", author: "Anna Chernyshova" },
  { text: "My candidate got a [X]-figure job offer. Here are [Y] ways to stop being overlooked in [event] 👇", author: "Anna Chernyshova" },
];
